apiVersion: apps/v1
kind: Deployment
metadata:
  name: oil-backend-deployment
  labels:
    app: oil-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oil-backend
  template:
    metadata:
      labels:
        app: oil-backend
    spec:
      containers:
        - name: oil-backend
          image: amdp-registry.skala-ai.com/skala25a/oil-backend:latest  # 백엔드 레포에서 푸시하는 경로
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONPATH
              value: /app
          envFrom:
            - secretRef:
                name: db-secret
            - configMapRef:
                name: db-config
      imagePullSecrets:
        - name: harbor-secret

