apiVersion: apps/v1
kind: Deployment
metadata:
  name: oil-backend-deployment
  labels:
    app: oil-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oil-backend
  template:
    metadata:
      labels:
        app: oil-backend
    spec:
      containers:
        - name: oil-backend
          image: amdp-registry.skala-ai.com/skala25a/oil-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONPATH
              value: /app
            - name: LANGCHAIN_PROJECT
              value: "CH14-Retriever"
            - name: MODEL
              value: "gpt-3.5-turbo"
            - name: DEBUG
              value: "False"
          envFrom:
            - secretRef:
                name: oil-backend-secret
            - secretRef:
                name: db-secret
            - configMapRef:
                name: db-config
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
      imagePullSecrets:
        - name: harbor-secret
