apiVersion: v1
kind: Service
metadata:
  name: oil-backend-service
  labels:
    app: oil-backend
spec:
  selector:
    app: oil-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP