apiVersion: v1
kind: Secret
metadata:
  name: oil-auth-secret
type: Opaque
stringData:
  DB_HOST: <YOUR_DB_HOST>
  DB_PORT: <YOUR_DB_PORT>
  DB_NAME: <YOUR_DB_NAME>
  DB_USERNAME: <YOUR_DB_USERNAME>
  DB_PASSWORD: <YOUR_DB_PASSWORD>
  DB_DRIVER: <YOUR_DB_DRIVER>
  JPA_DDL_AUTO: <YOUR_JPA_DDL_AUTO>
  JPA_FORMAT_SQL: <YOUR_JPA_FORMAT_SQL>
  JPA_SHOW_SQL: <YOUR_JPA_SHOW_SQL>
  JWT_SECRET: <YOUR_JWT_SECRET>
