apiVersion: apps/v1
kind: Deployment
metadata:
  name: oil-frontend-deployment
  labels:
    app: oil-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oil-frontend
  template:
    metadata:
      labels:
        app: oil-frontend
    spec:
      containers:
        - name: oil-frontend
          image: amdp-registry.skala-ai.com/skala25a/oil-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: oil-frontend-secret
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      imagePullSecrets:
        - name: harbor-secret

