apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhbWRwLXJlZ2lzdHJ5LnNrYWxhLWFpLmNvbSI6eyJ1c2VybmFtZSI6IlNrYWxhMjVhIiwicGFzc3dvcmQiOiJTa2FsYTI1YSEyMyQiLCJhdXRoIjoiVTJ0aGJHRXlOV0U2VTJ0aGJHRXlOV0VoTWpNayJ9fX0=