apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skala-app-ingress
  annotations:
    kubernetes.io/ingress.class: public-nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://oil-app.skala25a.project.skala-ai.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-max-age: "86400"
spec:
  tls:
    - hosts:
        - oil-app.skala25a.project.skala-ai.com
        - oil-api.skala25a.project.skala-ai.com
      secretName: oil-tls-secret
  rules:
    - host: oil-app.skala25a.project.skala-ai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oil-frontend-service
                port:
                  number: 3000
    - host: oil-api.skala25a.project.skala-ai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oil-backend-service
                port:
                  number: 8000
