apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skala-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: oil-app.skala25a.project.skala-ai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oil-frontend-service
                port:
                  number: 3000
    - host: oil-api.skala25a.project.skala-ai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oil-backend-service
                port:
                  number: 8000
