apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - harbor-secret.yaml
  - config-db.yaml

  # postgres
  - postgres/deployment.yaml
  - postgres/pvc.yaml
  - postgres/service.yaml

  # backend
  - backend/deployment.yaml
  - backend/service.yaml

  # frontend
  - frontend/deployment.yaml
  - frontend/service.yaml

  - ingress.yaml
