apiVersion: v1
kind: Service
metadata:
  name: oil-postgres-service
  labels:
    app: oil-postgres
spec:
  type: ClusterIP
  selector:
    app: oil-postgres
  ports:
    - port: 5432
      targetPort: 5432